### ISSUE TITLE
Support for the `Date` class

### ISSUE THREAD

**Issue by adamryczkowski** [larmarange/labelled#17]
I'd like to include tagged missings (NAs) in the Date variable. But when I do the following

```
x <- rep(c(1,2),5)
x[[4]] <- tagged_na('a')
y <- as.Date(x, origin = '1992-01-01')
class(y)
#[1] "Date"
labelled(y, c("NA"=tagged_na('a')))
#Error: 'y' must be a numeric or a character vector
```
Is this behavior by design, or do I write a valid feature request? :-)

**Comment by larmarange** [comment]
By design (and following the `haven` package), the `labelled` class could be apply only to numeric or character vector mut not to date.

Here, you are also mixing value labels and tagged_na which are two different systems. I guess you could use tagged_na with a date:

```
y <- as.Date(x, origin = '1992-01-01')
y[is.na(y)] <- tagged_na("a")
```

but you should refer to `haven`  package documentation.

Regards
